absoluteurl: http://www.ici3d.org
subdomainurl: http://www.ici3d.org/MMED
baseurl: /MMED
url: http://www.ici3d.org
title: MMED 2021
longtitle: Clinic on Meaningful Modeling of Epidemiological Data
summary: The eleventh annual MMED clinic  ~  June 28 - July 9, 2021  ~  Virtual edition
year: 2021
markdown: kramdown
highlighter: rouge
includes_dir: ICI3D.github.io/_includes
layouts_dir: ICI3D.github.io/_layouts
data_dir: ICI3D.github.io/_data
collections:
  talks:
    output: true
    permalink: /talks/:name/
  team:
    output: true
    permalink: /team/:name/
defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: team
    values:
      layout: profile
exclude:
  - redirect.html
  - README.md
  - run.sh
  - aims.sh
