absoluteurl: //www.ici3d.org
subdomainurl: //www.ici3d.org/MMED
baseurl: /MMED
url: //www.ici3d.org
title: MMED 2023
longtitle: Clinic on Meaningful Modeling of Epidemiological Data
summary: The twelfth MMED clinic  ~  June 26 - July 8, 2023  ~  Muizenberg, Cape Town, South Africa
year: 2023
theme: jekyll-theme-ici3d
markdown: kramdown
highlighter: rouge
collections:
  talks:
    output: true
    permalink: /talks/:name/
  team:
    output: true
    permalink: /team/:name/
defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: team
    values:
      layout: profile
exclude:
  - redirect.html
  - README.md
  - run.sh
  - aims.sh
